- hosts: datanode
  vars:
  - port_no: "9001"
  vars_prompt:
  - name: datanode_directory
    private: no
    prompt: "Enter datanode directory name"
  - name: namenode_ip
    private: no
    prompt: "enter master node IP"

  tasks:
  - name: "copying hadoop software"
    copy:
        src: "/root/hadoop-1.2.1-1.x86_64.rpm"
        dest: "/root/"

  - name: "copying java software"
    copy:
        src: "/root/jdk-8u171-linux-x64.rpm"
        dest: "/root/"

  - name: "Installing hadoop software"
    command: "rpm -ivh hadoop-1.2.1-1.x86_64.rpm --force"

  - name: "Installing java software"
    command: "rpm -ivh jdk-8u171-linux-x64.rpm --force"

  - name: "directory creation"
    file:
      state: directory
      path: "{{ datanode_directory }}"

  - name: "configuring hdfs-site.xml"
    blockinfile:
      path: "/etc/hadoop/hdfs-site.xml"
      insertafter: "<configuration>"
      block: 
        <property>
        <name>dfs.data.dir</name>
        <value>{{ datanode_directory }}</value>
        </property>

  - name: " configuring core-site.xml"
    blockinfile:
      path: "/etc/hadoop/core-site.xml"  
      insertafter: "<configuration>"
      block: 
        <property>
        <name>fs.default.name</name>
        <value>hdfs://{{ namenode_ip }}:9001</value>
        </property>

  - name: "starting hadoop datanode"
    command: "hadoop-daemon.sh start datanode"
